# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wines By Jeremy
email: winesbyjeremy@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Wines by Jeremy offers an educative and enjoyable personalized wine experience.
  Located in the DC metro area, Wines by Jeremy provides a number of services including in-home
  exclusive tastings, highly curated event tastings, educational events, and wine cellar consulting.
baseurl: ''
url: https://www.winesbyjeremy.com

# Social Accounts
facebook_username: winesbyjeremy
github_username: winesbyjeremy
instagram_username: winesbyjeremy
twitter_username: winesbyjeremy
vivino_username: winesbyjeremy

# Build settings
markdown: kramdown
#theme: jekyll-theme-architect
plugins:
  - jekyll-feed
  - jekyll-maps
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-auto-image

google_analytics: UA-123384548-1
mailchimp-list: //winesbyjeremy.us18.list-manage.com/subscribe/post?u=b22a07e976dd2efd7490276f9&amp;id=1e062452b6
maps:
  google:
    api_key: AIzaSyBGVILhPMYqclKhtLj2UKlORo40CnQp6wo
paginate: 10

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md

show_excerpts: true
